version: "2"

formatters:
  enable:
    - gofmt
    - goimports
    - golines

linters:
  default: "all"
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/viqueen/go-template
            - github.com/stretchr/testify
            - github.com/ovechkin-dm/mockio