name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.2

  build-and-test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 2.8.2
          args: build --clean --snapshot
